package com.inboundrx.paulsensbeaconsapp.sourceCode;

import com.inboundrx.paulsensbeaconsapp.BuildConfig;

/**
 * Created by arlen on 7/12/17.
 */

public class RouteConstants {
    public static final String BASE_URL = BuildConfig.BASE_URL;
    public static final String ROOT_PATH_GET = "/";
    public static final String HISTORICAL_EVENTS_PATH_GET = "/historical_events";
    public static final String HISTORICAL_EVENTS_PATH_POST = "/historical_events";
    public static final String NEW_HISTORICAL_EVENT_PATH_GET = "/historical_events/new";
    public static final String EDIT_HISTORICAL_EVENT_PATH_GET = "/historical_events/:id/edit";
    public static final String HISTORICAL_EVENT_PATH_ID_GET = "historical_events/:id";
    public static final String HISTORICAL_EVENT_PATH_ID_PATCH = "historical_events/:id";
    public static final String HISTORICAL_EVENT_PATH_ID_PUT = "historical_events/:id";
    public static final String HISTORICAL_EVENT_PATH_ID_DELETE = "historical_events/:id";
    public static final String PRODUCTS_PATH_GET = "/products";
    public static final String PRODUCTS_PATH_POST = "/products";
    public static final String NEW_PRODUCTS_PATH_GET = "/products/new";
    public static final String EDIT_PRODUCTS_PATH_GET = "/products/edit";
    public static final String PRODUCTS_PATH_ID_GET = "/products/:id";
    public static final String PRODUCTS_PATH_ID_PATCH = "/products/:id";
    public static final String PRODUCTS_PATH_ID_PUT = "/products/:id";
    public static final String PRODUCTS_PATH_ID_DELETE = "/products/:id";
    public static final String PROMOTIONS_PATH_GET = "/promotions";
    public static final String PROMOTIONS_PATH_POST = "/promotions";
    public static final String NEW_PROMOTION_PATH_GET = "/promotions/new";
    public static final String EDIT_PROMOTION_PATH_GET = "/promotions/:id/edit";
    public static final String PROMOTION_PATH_ID_GET = "/promotions/:id";
    public static final String PROMOTION_PATH_ID_PATCH = "/promotions/:id";
    public static final String PROMOTION_PATH_ID_PUT = "/promotions/:id";
    public static final String PROMOTION_PATH_ID_DELETE = "/promotions/:id";
    public static final String ROLES_PATH_GET = "/roles";
    public static final String ROLES_PATH_POST = "/roles";
    public static final String NEW_ROLE_PATH_GET = "/roles/new";
    public static final String EDIT_ROLE_PATH_GET = "/roles/:id/edit";
    public static final String ROLES_PATH_ID_PATCH = "/roles/:id";
    public static final String ROLES_PATH_ID_PUT = "/roles/:id";
    public static final String ROLES_PATH_ID_DELETE = "/roles/:id";
    public static final String CREDITS_PATH_GET = "/credits";
    public static final String EDIT_CREDIT_PATH_ID_GET = "/credits/:id/edit";
    public static final String CREDIT_PATH_ID_GET = "/credits/:id";
    public static final String CREDIT_PATH_ID_PATCH = "/credits/:id";
    public static final String CREDIT_PATH_ID_PUT = "/credits/:id";
    public static final String CREDIT_PATH_ID_DELETE = "/credits/:id";
    public static final String REWARD_RESOURCE_STATE_CHANGE_PATH_PATCH = "/rewards/:reward_id/status";
    public static final String REWARDS_PATH_GET = "/rewards";
    public static final String REWARDS_PATH_POST = "/rewards";
    public static final String NEW_REWARD_PATH_GET = "/rewards/:id/new";
    public static final String EDIT_REWARD_PATH_GET = "/rewards/:id/edit";
    public static final String REWARD_PATH_ID_GET = "/rewards/:id";
    public static final String REWARD_PATH_ID_PATCH = "/rewards/:id";
    public static final String REWARD_PATH_ID_PUT = "/rewards/:id";
    public static final String REWARD_PATH_ID_DELETE = "/rewards/:id";
    public static final String NOTIFICATION_RESOURCE_STATE_CHANGE_PATH_PATCH = "/notifications/:notification_id/status";
    public static final String NOTIFICATIONS_PATH_GET = "/notifications";
    public static final String NOTIFICATIONS_PATH_POST = "/notifications";
    public static final String NEW_NOTIFICATIONS_PATH_GET = "/notifications/:id/new";
    public static final String EDIT_NOTIFICATIONS_PATH_GET = "/notifications/:id/edit";
    public static final String NOTIFICATION_PATH_ID_GET = "/notifications/:id";
    public static final String NOTIFICATION_PATH_ID_PATCH = "/notifications/:id";
    public static final String NOTIFICATION_PATH_ID_PUT = "/notifications/:id";
    public static final String NOTIFICATION_PATH_ID_DELETE = "/notifications/:id";
    public static final String ORDER_RESOURCE_STATE_CHANGE_PATH_PATCH = "/orders/:order_id/status";
    public static final String ORDERS_PATH_GET = "/orders";
    public static final String ORDERS_PATH_POST = "/orders";
    public static final String NEW_ORDER_PATH_GET = "/orders/:id/new";
    public static final String EDIT_ORDER_PATH_GET = "/orders/:id/edit";
    public static final String ORDER_PATH_ID_GET = "/orders/:id";
    public static final String ORDER_PATH_ID_PATCH = "/orders/:id";
    public static final String ORDER_PATH_ID_PUT = "/orders/:id";
    public static final String ORDER_PATH_ID_DELETE = "/orders/:id";
    public static final String BEACON_RESOURCE_STATE_CHANGE_PATH_PATCH = "/orders/:order_id/status";
    public static final String BEACON_NOTIFICATION_PATH_GET = "/beacons/:beacon_id/notifications";
    public static final String BEACON_NOTIFICATION_PATH_POST = "/beacons/:beacon_id/notifications";
    public static final String NEW_BEACON_NOTIFICATION_PATH_GET = "/beacons/:beacon_id/notifications/:id/new";
    public static final String EDIT_BEACON_NOTIFICATION_PATH_GET = "/beacons/:beacon_id/notifications/:id/edit";
    public static final String BEACON_NOTIFICATION_PATH_ID_GET = "/beacons/:beacon_id/notifications/:id";
    public static final String BEACON_NOTIFICATION_PATH_ID_PATCH = "/beacons/:beacon_id/notifications/:id";
    public static final String BEACON_NOTIFICATION_PATH_ID_PUT = "/beacons/:beacon_id/notifications/:id";
    public static final String BEACON_NOTIFICATION_PATH_ID_DELETE = "/beacons/:beacon_id/notifications/:id";
    public static final String BEACONS_PATH_GET = "/beacons";
    public static final String BEACONS_PATH_POST = "/beacons";
    public static final String NEW_BEACON_PATH_GET = "/beacons/new";
    public static final String EDIT_BEACON_PATH_GET = "/beacons/:id/edit";
    public static final String ORDER_BEACON_ID_GET = "/beacons/:id";
    public static final String ORDER_BEACON_ID_PATCH = "/beacons/:id";
    public static final String ORDER_BEACON_ID_PUT = "/beacons/:id";
    public static final String ORDER_BEACON_ID_DELETE = "/beacons/:id";

    public static final String API_DESTROY_USER_SESSION_PATH_DELETE="api/logout";
    public static final String API_USER_SESSION_PATH_POST= "api/login";
    public static final String ACCOUNT_REWARDS_PATH_GET= "account/rewards";
    public static final String ACCOUNT_CREDITS_PATH_GET="account/credits";
    public static final String ACCOUNT_PATH_GET="account";
    public static final String DESTROY_USER_SESSION_PATH_DELETE="logout";
    public static final String USER_SESSION_PATH_POST="login";
    public static final String NEW_USER_SESSION_PATH_GET="/login";
    public static final String USER_PATH_GET="/users/:id";
    public static final String EDIT_USER_PATH_GET="/users/:id/edit";
    public static final String NEW_USER_PATH_GET="users/new";
    public static final String USERS_PATH_GET="/users";
    public static final String USER_REGISTRATION_PATH_PATCH="/account";
    public static final String EDIT_USER_REGISTRATION_PATH="/account/edit";
    public static final String NEW_USER_REGISTRATION_PATH_GET="/account/sign_up";
    public static final String CANCEL_USER_REGISTRATION_GET="account/deactivate";
    public static final String USER_PASSWORD_PATH_PATCH="account/password";
    public static final String EDIT_USER_PASSWORD_PATH_GET="/account/password/edit";
    public static final String NEW_USER_PASSWORD_PATH_GET="/account/password/new";
}
